version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    #read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    ports:
      - 9117:9117
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
      # launch using the command line arguments, IE pick one:
      - ./config:/vpn
    # command: 'server;user;password[;port]'
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    depends_on:
      - vpn
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    network_mode: "service:vpn"
    volumes:
      - ~/data/jackett/config:/config
      - ~/data/jackett/blackhole:/downloads
    #    ports:
    #      - 9117:9117
    restart: unless-stopped
    stdin_open: true

  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    container_name: torrserver
    volumes:
      - ./data/torrserve/:/opt/ts
    environment:
      - TS_HTTPAUTH=1
    ports:
      - 8090:8090
    restart: unless-stopped

networks:
  default:

